---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Streaming Session - Part 0 - Bastion"

Parameters:
  ResourcePrefix:
    Type: "String"
    Description: "Prefix added to all created resources"
    AllowedPattern: "[a-zA-Z0-9-]+"

  Keypair:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: "Your personal SSH keypair"

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Default: "vpc-4afffa2d"

  SubnetId:
    Type: "AWS::EC2::Subnet::Id"
    Default: "subnet-30688556"

  LatestAMIId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

Resources:
  BastionSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${ResourcePrefix}-bastion-sg"
      GroupDescription: "Streaming Bastion SG"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow inbound SSH"
          FromPort: 22
          IpProtocol: "tcp"
          ToPort: 22
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow internet access"
          IpProtocol: "-1"
      Tags:
        - Key: "SessionName"
          Value: "Streaming"
        - Key: "SessionPart"
          Value: "0"
      VpcId: !Ref VpcId

  BastionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: mskaccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kafka:*
                  - kinesis:*
                Resource:
                  - "*"

  BastionInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref BastionRole

  BastionEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      IamInstanceProfile: !Ref BastionInstanceProfile
      ImageId: !Ref LatestAMIId
      InstanceType: "t3.micro"
      KeyName: !Ref Keypair
      SecurityGroupIds:
        - !Ref BastionSG
      SubnetId: !Ref SubnetId
      Tags:
        - Key: "SessionName"
          Value: "Streaming"
        - Key: "SessionPart"
          Value: "0"
        - Key: "Name"
          Value: !Sub "${ResourcePrefix}-bastion"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -ex
            yum update -y
            yum install -y python3 python3-pip git vim
            pip3 install --upgrade boto3
            pip3 install kafka-python==2.0.1
            pip3 install requests

            pushd /home/ec2-user
            git clone https://github.com/michael-robbins/aws-streaming-session.git
            chown -R ec2-user:ec2-user aws-streaming-session

            echo '{ "prefix": "${ResourcePrefix}" }' > aws-streaming-session/resource_prefix.json
            chown ec2-user:ec2-user aws-streaming-session/resource_prefix.json

            mkdir .aws
            echo -e '[default]\nregion = ${AWS::Region}' > .aws/config
            chown ec2-user:ec2-user .aws/config
            popd

Outputs:
  BastionSG:
    Description: Security Group ID of the Bastion
    Value: !Ref BastionSG
    Export:
      Name: !Sub "${ResourcePrefix}-bastion-sg"
