---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Streaming Session - Part 0 - Bastion"

Parameters:
  ResourcePrefix:
    Type: "String"
    Description: "Prefix added to all created resources"
    AllowedPattern: "[a-zA-Z0-9-]+"

  Keypair:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: "Your personal SSH keypair"

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Default: "vpc-4afffa2d"

  SubnetId:
    Type: "AWS::EC2::Subnet::Id"
    Default: "subnet-30688556"

  LatestAMIId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

Resources:
  BastionSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${ResourcePrefix}-bastion-sg"
      GroupDescription: "Streaming Bastion SG"
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow all outbound access"
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow inbound SSH"
          FromPort: 22
          IpProtocol: "tcp"
          ToPort: 22
      Tags:
        - Key: "SessionName"
          Value: "Streaming"
        - Key: "SessionPart"
          Value: "0"
      VpcId: !Ref VpcId

  BastionEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref LatestAMIId
      InstanceType: "t3.micro"
      KeyName: !Ref Keypair
      SecurityGroupIds:
        - !Ref BastionSG
      SubnetId: !Ref SubnetId
      Tags:
        - Key: "SessionName"
          Value: "Streaming"
        - Key: "SessionPart"
          Value: "0"
        - Key: "Name"
          Value: !Sub "${ResourcePrefix}-bastion"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -ex
            yum update -y
            yum install -y python3 python3-pip git vim
            pip3 install kafka-python==2.0.1

            su - ec2-user
            pushd /home/ec2-user
            git clone https://github.com/michael-robbins/aws-streaming-session.git
            popd

Outputs:
  BastionSG:
    Description: Security Group ID of the Bastion
    Value: !Ref BastionSG
    Export:
      Name: !Sub "${ResourcePrefix}-bastion-sg"
